# Storage
filestore:
  build: .docker/sshd
  volumes:
    - /var/www
db:
  image: mariadb:10.0
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - ./.docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  expose:
    - "3306"

# Services
php:
  image: davenuman/bowline-centos
  command: php-fpm
  environment:
    - COMPOSER_HOME=/.composer
  expose:
    - "9000"
  volumes_from:
    - filestore
  links:
    - db:dbhost
  hostname: php_host
web:
  image: davenuman/bowline-centos
  command: httpd -D FOREGROUND -e debug
  expose:
    - "80"
  links:
    - db:dbhost
    - php:php_host
  hostname: drupal
  volumes_from:
    - filestore

# File synchronizing
sync:
  build: .docker/osync
  command: /start.sh
  links:
    - filestore:filestore
  volumes:
    - ./docroot:/var/www/docroot
    - .ssh:/tmp/keys
  hostname: sync

