sync:
  image: tianon/syncthing
  command: syncthing -gui-address=0.0.0.0:8384
  hostname: sync-container
  volumes:
    - /home/user
sync_cli:
  image: tianon/syncthing-cli
  hostname: sync-cli
  links:
    - sync:sync

db:
  image: mariadb:10.0
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - ./.docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  expose:
    - "3306"
php:
  image: davenuman/bowline-centos
  command: php-fpm
  environment:
    - COMPOSER_HOME=/.composer
  expose:
    - "9000"
  links:
    - db:dbhost
  volumes_from:
    - sync
  hostname: php_host
web:
  image: davenuman/bowline-centos
  command: httpd -D FOREGROUND -e debug
  expose:
    - "80"
  links:
    - db:dbhost
    - php:php_host
  volumes_from:
    - sync
  hostname: drupal
